[package]
name = "rust-hypervisor"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.171"
nix = { version = "0.29.0", features = ["fs", "mman"] }
num-traits = "0.2.19"
thiserror = "2.0.12"

[build-dependencies]
bindgen = "0.71.1"
